db:
  build: ./docker_database
  command: /startup.sh
  volumes:
    - ./docker_database/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456

weba:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/webapp
  expose:
    - 3000
  ports:
    - "3000:3000"
  links:
    - db:mysql_database
