合肥市: ["长丰县", "肥东县", "巢湖市", "庐江县", "肥西县", "庐阳区", "包河区", "蜀山区"]
安庆市: ["迎江区", "大观区", "宜秀区", "怀宁县", "潜山县", "宿松县", "太湖县", "桐城市", "望江县", "岳西县"]
黄山市: ["黄山区", "祁门县", "屯溪区", "徽州区", "歙县", "休宁县", "黟县"]
六安市: ["霍邱县", "霍山县", "金安区", "裕安区", "金寨县", "舒城县", "寿县"]
马鞍山市: ["当涂县", "和县", "含山县", "花山区", "雨山区"]
宿州市: ["砀山县", "灵璧县", "埇桥区", "泗县", "萧县"]
铜陵市: ["铜官山区", "铜陵县", "狮子山区", "郊区"]
芜湖市: ["繁昌县", "南陵县", "无为县", "镜湖区", "弋江区", "鸠江区", "三山区", "芜湖县"] 
宣城市: ["广德县", "绩溪县", "宣州区", "泾县", "旌德县", "郎溪县", "宁国市"] 
蚌埠市: ["固镇县", "龙子湖区", "蚌山区", "禹会区", "淮上区", "怀远县", "五河县"]
亳州市: ["利辛县", "谯城区", "蒙城区", "涡阳县"]
池州市: ["青阳县", "贵池区", "石台县", "东至县"]
滁州市: ["定远县", "琅琊区", "南谯区", "凤阳县", "来安县", "明光市", "全椒县", "天长市"]
阜阳市: ["阜南县", "颍州区", "颍东区", "颍泉区", "开发区", "界首市", "临泉县", "太和县", "颍上县"]
淮北市: ["濉溪县", "相山区", "杜集区", "烈山区"]
淮南市: ["凤台县", "大通区", "田家庵区", "谢家集区", "八公山区", "潘集区"]
total: ["长丰县", "肥东县", "巢湖市", "庐江县", "肥西县", "庐阳区", "包河区", "蜀山区", "迎江区", "大观区", "宜秀区", "怀宁县", "潜山县", "宿松县", "太湖县", "桐城市", "望江县", "岳西县", "黄山区", "祁门县", "屯溪区", "徽州区", "歙县", "休宁县", "黟县", "霍邱县", "霍山县", "金安区", "裕安区", "金寨县", "舒城县", "寿县", "当涂县", "和县", "含山县", "花山区", "雨山区", "砀山县", "灵璧县", "埇桥区", "泗县", "萧县", "铜官山区", "铜陵县", "狮子山区", "郊区", "繁昌县", "南陵县", "无为县", "镜湖区", "弋江区", "鸠江区", "三山区", "芜湖县", "广德县", "绩溪县", "宣州区", "泾县", "旌德县", "郎溪县", "宁国市", "固镇县", "龙子湖区", "蚌山区", "禹会区", "淮上区", "怀远县", "五河县", "利辛县", "谯城区", "蒙城区", "涡阳县", "青阳县", "贵池区", "石台县", "东至县", "定远县", "琅琊区", "南谯区", "凤阳县", "来安县", "明光市", "全椒县", "天长市", "阜南县", "颍州区", "颍东区", "颍泉区", "开发区", "界首市", "临泉县", "太和县", "颍上县", "濉溪县", "相山区", "杜集区", "烈山区", "凤台县", "大通区", "田家庵区", "谢家集区", "八公山区", "潘集区"]
