# MySQL.  Versions 5.6+ recommended.
development:
  adapter: mysql2
  #host: mysql_database
  encoding: utf8
  reconnect: false
  database: depot_demo_production
  pool: 25
  username: root
  password: btbuzuomin5638

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: depot_demo_production
  pool: 25
  username: root
  password: btbuzuomin5638
