# MySQL.  Versions 5.6+ recommended.
development:
  adapter: mysql2
  #host: mysql_database
  encoding: utf8
  reconnect: false
  database: tdepot_demo_production
  pool: 25
  #host: '10.0.39.208'
  username: root
  password: 123456

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tdepot_demo_production
  pool: 25
  #host: '10.0.39.208'
  username: root
  password: 123456
