# MySQL.  Versions 5.6+ recommended.
development:
  adapter: mysql2
  #host: mysql_database
  encoding: utf8
  reconnect: false
  database: jilin_ceshi
  pool: 25
  username: root
  password: BJzyd82510

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jilin_ceshi
  pool: 25
  username: root
  password: BJzyd82510
