class Add141ToSpBsbs < ActiveRecord::Migration
  def change
      add_column :sp_bsbs, :sp_s_141_0, :text
      add_column :sp_bsbs, :sp_s_141_1, :text
      add_column :sp_bsbs, :sp_s_141_2, :text
      add_column :sp_bsbs, :sp_s_141_3, :text
      add_column :sp_bsbs, :sp_s_141_4, :text
      add_column :sp_bsbs, :sp_s_141_5, :text
      add_column :sp_bsbs, :sp_s_141_6, :text
      add_column :sp_bsbs, :sp_s_141_7, :text
      add_column :sp_bsbs, :sp_s_141_8, :text
      add_column :sp_bsbs, :sp_s_141_9, :text
      add_column :sp_bsbs, :sp_s_142_0, :text
      add_column :sp_bsbs, :sp_s_142_1, :text
      add_column :sp_bsbs, :sp_s_142_2, :text
      add_column :sp_bsbs, :sp_s_142_3, :text
      add_column :sp_bsbs, :sp_s_142_4, :text
      add_column :sp_bsbs, :sp_s_142_5, :text
      add_column :sp_bsbs, :sp_s_142_6, :text
      add_column :sp_bsbs, :sp_s_142_7, :text
      add_column :sp_bsbs, :sp_s_142_8, :text
      add_column :sp_bsbs, :sp_s_142_9, :text
      add_column :sp_bsbs, :sp_s_143_0, :text
      add_column :sp_bsbs, :sp_s_143_1, :text
      add_column :sp_bsbs, :sp_s_143_2, :text
      add_column :sp_bsbs, :sp_s_143_3, :text
      add_column :sp_bsbs, :sp_s_143_4, :text
      add_column :sp_bsbs, :sp_s_143_5, :text
      add_column :sp_bsbs, :sp_s_143_6, :text
      add_column :sp_bsbs, :sp_s_143_7, :text
      add_column :sp_bsbs, :sp_s_143_8, :text
      add_column :sp_bsbs, :sp_s_143_9, :text
      add_column :sp_bsbs, :sp_s_144_0, :text
      add_column :sp_bsbs, :sp_s_144_1, :text
      add_column :sp_bsbs, :sp_s_144_2, :text
      add_column :sp_bsbs, :sp_s_144_3, :text
      add_column :sp_bsbs, :sp_s_144_4, :text
      add_column :sp_bsbs, :sp_s_144_5, :text
      add_column :sp_bsbs, :sp_s_144_6, :text
      add_column :sp_bsbs, :sp_s_144_7, :text
      add_column :sp_bsbs, :sp_s_144_8, :text
      add_column :sp_bsbs, :sp_s_144_9, :text
      add_column :sp_bsbs, :sp_s_145_0, :text
      add_column :sp_bsbs, :sp_s_145_1, :text
      add_column :sp_bsbs, :sp_s_145_2, :text
      add_column :sp_bsbs, :sp_s_145_3, :text
      add_column :sp_bsbs, :sp_s_145_4, :text
      add_column :sp_bsbs, :sp_s_145_5, :text
      add_column :sp_bsbs, :sp_s_145_6, :text
      add_column :sp_bsbs, :sp_s_145_7, :text
      add_column :sp_bsbs, :sp_s_145_8, :text
      add_column :sp_bsbs, :sp_s_145_9, :text
      add_column :sp_bsbs, :sp_s_146_0, :text
      add_column :sp_bsbs, :sp_s_146_1, :text
      add_column :sp_bsbs, :sp_s_146_2, :text
      add_column :sp_bsbs, :sp_s_146_3, :text
      add_column :sp_bsbs, :sp_s_146_4, :text
      add_column :sp_bsbs, :sp_s_146_5, :text
      add_column :sp_bsbs, :sp_s_146_6, :text
      add_column :sp_bsbs, :sp_s_146_7, :text
      add_column :sp_bsbs, :sp_s_146_8, :text
      add_column :sp_bsbs, :sp_s_146_9, :text
      add_column :sp_bsbs, :sp_s_147_0, :text
      add_column :sp_bsbs, :sp_s_147_1, :text
      add_column :sp_bsbs, :sp_s_147_2, :text
      add_column :sp_bsbs, :sp_s_147_3, :text
      add_column :sp_bsbs, :sp_s_147_4, :text
      add_column :sp_bsbs, :sp_s_147_5, :text
      add_column :sp_bsbs, :sp_s_147_6, :text
      add_column :sp_bsbs, :sp_s_147_7, :text
      add_column :sp_bsbs, :sp_s_147_8, :text
      add_column :sp_bsbs, :sp_s_147_9, :text
      add_column :sp_bsbs, :sp_s_148_0, :text
      add_column :sp_bsbs, :sp_s_148_1, :text
      add_column :sp_bsbs, :sp_s_148_2, :text
      add_column :sp_bsbs, :sp_s_148_3, :text
      add_column :sp_bsbs, :sp_s_148_4, :text
      add_column :sp_bsbs, :sp_s_148_5, :text
      add_column :sp_bsbs, :sp_s_148_6, :text
      add_column :sp_bsbs, :sp_s_148_7, :text
      add_column :sp_bsbs, :sp_s_148_8, :text
      add_column :sp_bsbs, :sp_s_148_9, :text
      add_column :sp_bsbs, :sp_s_149_0, :text
      add_column :sp_bsbs, :sp_s_149_1, :text
      add_column :sp_bsbs, :sp_s_149_2, :text
      add_column :sp_bsbs, :sp_s_149_3, :text
      add_column :sp_bsbs, :sp_s_149_4, :text
      add_column :sp_bsbs, :sp_s_149_5, :text
      add_column :sp_bsbs, :sp_s_149_6, :text
      add_column :sp_bsbs, :sp_s_149_7, :text
      add_column :sp_bsbs, :sp_s_149_8, :text
      add_column :sp_bsbs, :sp_s_149_9, :text
      add_column :sp_bsbs, :sp_s_150_0, :text
      add_column :sp_bsbs, :sp_s_150_1, :text
      add_column :sp_bsbs, :sp_s_150_2, :text
      add_column :sp_bsbs, :sp_s_150_3, :text
      add_column :sp_bsbs, :sp_s_150_4, :text
      add_column :sp_bsbs, :sp_s_150_5, :text
      add_column :sp_bsbs, :sp_s_150_6, :text
      add_column :sp_bsbs, :sp_s_150_7, :text
      add_column :sp_bsbs, :sp_s_150_8, :text
      add_column :sp_bsbs, :sp_s_150_9, :text
      add_column :sp_bsbs, :sp_s_151_0, :text
      add_column :sp_bsbs, :sp_s_151_1, :text
      add_column :sp_bsbs, :sp_s_151_2, :text
      add_column :sp_bsbs, :sp_s_151_3, :text
      add_column :sp_bsbs, :sp_s_151_4, :text
      add_column :sp_bsbs, :sp_s_151_5, :text
      add_column :sp_bsbs, :sp_s_151_6, :text
      add_column :sp_bsbs, :sp_s_151_7, :text
      add_column :sp_bsbs, :sp_s_151_8, :text
      add_column :sp_bsbs, :sp_s_151_9, :text
      add_column :sp_bsbs, :sp_s_152_0, :text
      add_column :sp_bsbs, :sp_s_152_1, :text
      add_column :sp_bsbs, :sp_s_152_2, :text
      add_column :sp_bsbs, :sp_s_152_3, :text
      add_column :sp_bsbs, :sp_s_152_4, :text
      add_column :sp_bsbs, :sp_s_152_5, :text
      add_column :sp_bsbs, :sp_s_152_6, :text
      add_column :sp_bsbs, :sp_s_152_7, :text
      add_column :sp_bsbs, :sp_s_152_8, :text
      add_column :sp_bsbs, :sp_s_152_9, :text
      add_column :sp_bsbs, :sp_s_153_0, :text
      add_column :sp_bsbs, :sp_s_153_1, :text
      add_column :sp_bsbs, :sp_s_153_2, :text
      add_column :sp_bsbs, :sp_s_153_3, :text
      add_column :sp_bsbs, :sp_s_153_4, :text
      add_column :sp_bsbs, :sp_s_153_5, :text
      add_column :sp_bsbs, :sp_s_153_6, :text
      add_column :sp_bsbs, :sp_s_153_7, :text
      add_column :sp_bsbs, :sp_s_153_8, :text
      add_column :sp_bsbs, :sp_s_153_9, :text
      add_column :sp_bsbs, :sp_s_154_0, :text
      add_column :sp_bsbs, :sp_s_154_1, :text
      add_column :sp_bsbs, :sp_s_154_2, :text
      add_column :sp_bsbs, :sp_s_154_3, :text
      add_column :sp_bsbs, :sp_s_154_4, :text
      add_column :sp_bsbs, :sp_s_154_5, :text
      add_column :sp_bsbs, :sp_s_154_6, :text
      add_column :sp_bsbs, :sp_s_154_7, :text
      add_column :sp_bsbs, :sp_s_154_8, :text
      add_column :sp_bsbs, :sp_s_154_9, :text
      add_column :sp_bsbs, :sp_s_155_0, :text
      add_column :sp_bsbs, :sp_s_155_1, :text
      add_column :sp_bsbs, :sp_s_155_2, :text
      add_column :sp_bsbs, :sp_s_155_3, :text
      add_column :sp_bsbs, :sp_s_155_4, :text
      add_column :sp_bsbs, :sp_s_155_5, :text
      add_column :sp_bsbs, :sp_s_155_6, :text
      add_column :sp_bsbs, :sp_s_155_7, :text
      add_column :sp_bsbs, :sp_s_155_8, :text
      add_column :sp_bsbs, :sp_s_155_9, :text
      add_column :sp_bsbs, :sp_s_156_0, :text
      add_column :sp_bsbs, :sp_s_156_1, :text
      add_column :sp_bsbs, :sp_s_156_2, :text
      add_column :sp_bsbs, :sp_s_156_3, :text
      add_column :sp_bsbs, :sp_s_156_4, :text
      add_column :sp_bsbs, :sp_s_156_5, :text
      add_column :sp_bsbs, :sp_s_156_6, :text
      add_column :sp_bsbs, :sp_s_156_7, :text
      add_column :sp_bsbs, :sp_s_156_8, :text
      add_column :sp_bsbs, :sp_s_156_9, :text
      add_column :sp_bsbs, :sp_s_157_0, :text
      add_column :sp_bsbs, :sp_s_157_1, :text
      add_column :sp_bsbs, :sp_s_157_2, :text
      add_column :sp_bsbs, :sp_s_157_3, :text
      add_column :sp_bsbs, :sp_s_157_4, :text
      add_column :sp_bsbs, :sp_s_157_5, :text
      add_column :sp_bsbs, :sp_s_157_6, :text
      add_column :sp_bsbs, :sp_s_157_7, :text
      add_column :sp_bsbs, :sp_s_157_8, :text
      add_column :sp_bsbs, :sp_s_157_9, :text
      add_column :sp_bsbs, :sp_s_158_0, :text
      add_column :sp_bsbs, :sp_s_158_1, :text
      add_column :sp_bsbs, :sp_s_158_2, :text
      add_column :sp_bsbs, :sp_s_158_3, :text
      add_column :sp_bsbs, :sp_s_158_4, :text
      add_column :sp_bsbs, :sp_s_158_5, :text
      add_column :sp_bsbs, :sp_s_158_6, :text
      add_column :sp_bsbs, :sp_s_158_7, :text
      add_column :sp_bsbs, :sp_s_158_8, :text
      add_column :sp_bsbs, :sp_s_158_9, :text
      add_column :sp_bsbs, :sp_s_159_0, :text
      add_column :sp_bsbs, :sp_s_159_1, :text
      add_column :sp_bsbs, :sp_s_159_2, :text
      add_column :sp_bsbs, :sp_s_159_3, :text
      add_column :sp_bsbs, :sp_s_159_4, :text
      add_column :sp_bsbs, :sp_s_159_5, :text
      add_column :sp_bsbs, :sp_s_159_6, :text
      add_column :sp_bsbs, :sp_s_159_7, :text
      add_column :sp_bsbs, :sp_s_159_8, :text
      add_column :sp_bsbs, :sp_s_159_9, :text
      add_column :sp_bsbs, :sp_s_160_0, :text
      add_column :sp_bsbs, :sp_s_160_1, :text
      add_column :sp_bsbs, :sp_s_160_2, :text
      add_column :sp_bsbs, :sp_s_160_3, :text
      add_column :sp_bsbs, :sp_s_160_4, :text
      add_column :sp_bsbs, :sp_s_160_5, :text
      add_column :sp_bsbs, :sp_s_160_6, :text
      add_column :sp_bsbs, :sp_s_160_7, :text
      add_column :sp_bsbs, :sp_s_160_8, :text
      add_column :sp_bsbs, :sp_s_160_9, :text
      add_column :sp_bsbs, :sp_s_161_0, :text
      add_column :sp_bsbs, :sp_s_161_1, :text
      add_column :sp_bsbs, :sp_s_161_2, :text
      add_column :sp_bsbs, :sp_s_161_3, :text
      add_column :sp_bsbs, :sp_s_161_4, :text
      add_column :sp_bsbs, :sp_s_161_5, :text
      add_column :sp_bsbs, :sp_s_161_6, :text
      add_column :sp_bsbs, :sp_s_161_7, :text
      add_column :sp_bsbs, :sp_s_161_8, :text
      add_column :sp_bsbs, :sp_s_161_9, :text
      add_column :sp_bsbs, :sp_s_162_0, :text
      add_column :sp_bsbs, :sp_s_162_1, :text
      add_column :sp_bsbs, :sp_s_162_2, :text
      add_column :sp_bsbs, :sp_s_162_3, :text
      add_column :sp_bsbs, :sp_s_162_4, :text
      add_column :sp_bsbs, :sp_s_162_5, :text
      add_column :sp_bsbs, :sp_s_162_6, :text
      add_column :sp_bsbs, :sp_s_162_7, :text
      add_column :sp_bsbs, :sp_s_162_8, :text
      add_column :sp_bsbs, :sp_s_162_9, :text
      add_column :sp_bsbs, :sp_s_163_0, :text
      add_column :sp_bsbs, :sp_s_163_1, :text
      add_column :sp_bsbs, :sp_s_163_2, :text
      add_column :sp_bsbs, :sp_s_163_3, :text
      add_column :sp_bsbs, :sp_s_163_4, :text
      add_column :sp_bsbs, :sp_s_163_5, :text
      add_column :sp_bsbs, :sp_s_163_6, :text
      add_column :sp_bsbs, :sp_s_163_7, :text
      add_column :sp_bsbs, :sp_s_163_8, :text
      add_column :sp_bsbs, :sp_s_163_9, :text
      add_column :sp_bsbs, :sp_s_164_0, :text
      add_column :sp_bsbs, :sp_s_164_1, :text
      add_column :sp_bsbs, :sp_s_164_2, :text
      add_column :sp_bsbs, :sp_s_164_3, :text
      add_column :sp_bsbs, :sp_s_164_4, :text
      add_column :sp_bsbs, :sp_s_164_5, :text
      add_column :sp_bsbs, :sp_s_164_6, :text
      add_column :sp_bsbs, :sp_s_164_7, :text
      add_column :sp_bsbs, :sp_s_164_8, :text
      add_column :sp_bsbs, :sp_s_164_9, :text
      add_column :sp_bsbs, :sp_s_165_0, :text
      add_column :sp_bsbs, :sp_s_165_1, :text
      add_column :sp_bsbs, :sp_s_165_2, :text
      add_column :sp_bsbs, :sp_s_165_3, :text
      add_column :sp_bsbs, :sp_s_165_4, :text
      add_column :sp_bsbs, :sp_s_165_5, :text
      add_column :sp_bsbs, :sp_s_165_6, :text
      add_column :sp_bsbs, :sp_s_165_7, :text
      add_column :sp_bsbs, :sp_s_165_8, :text
      add_column :sp_bsbs, :sp_s_165_9, :text
      add_column :sp_bsbs, :sp_s_166_0, :text
      add_column :sp_bsbs, :sp_s_166_1, :text
      add_column :sp_bsbs, :sp_s_166_2, :text
      add_column :sp_bsbs, :sp_s_166_3, :text
      add_column :sp_bsbs, :sp_s_166_4, :text
      add_column :sp_bsbs, :sp_s_166_5, :text
      add_column :sp_bsbs, :sp_s_166_6, :text
      add_column :sp_bsbs, :sp_s_166_7, :text
      add_column :sp_bsbs, :sp_s_166_8, :text
      add_column :sp_bsbs, :sp_s_166_9, :text
      add_column :sp_bsbs, :sp_s_167_0, :text
      add_column :sp_bsbs, :sp_s_167_1, :text
      add_column :sp_bsbs, :sp_s_167_2, :text
      add_column :sp_bsbs, :sp_s_167_3, :text
      add_column :sp_bsbs, :sp_s_167_4, :text
      add_column :sp_bsbs, :sp_s_167_5, :text
      add_column :sp_bsbs, :sp_s_167_6, :text
      add_column :sp_bsbs, :sp_s_167_7, :text
      add_column :sp_bsbs, :sp_s_167_8, :text
      add_column :sp_bsbs, :sp_s_167_9, :text
      add_column :sp_bsbs, :sp_s_168_0, :text
      add_column :sp_bsbs, :sp_s_168_1, :text
      add_column :sp_bsbs, :sp_s_168_2, :text
      add_column :sp_bsbs, :sp_s_168_3, :text
      add_column :sp_bsbs, :sp_s_168_4, :text
      add_column :sp_bsbs, :sp_s_168_5, :text
      add_column :sp_bsbs, :sp_s_168_6, :text
      add_column :sp_bsbs, :sp_s_168_7, :text
      add_column :sp_bsbs, :sp_s_168_8, :text
      add_column :sp_bsbs, :sp_s_168_9, :text
      add_column :sp_bsbs, :sp_s_169_0, :text
      add_column :sp_bsbs, :sp_s_169_1, :text
      add_column :sp_bsbs, :sp_s_169_2, :text
      add_column :sp_bsbs, :sp_s_169_3, :text
      add_column :sp_bsbs, :sp_s_169_4, :text
      add_column :sp_bsbs, :sp_s_169_5, :text
      add_column :sp_bsbs, :sp_s_169_6, :text
      add_column :sp_bsbs, :sp_s_169_7, :text
      add_column :sp_bsbs, :sp_s_169_8, :text
      add_column :sp_bsbs, :sp_s_169_9, :text
      add_column :sp_bsbs, :sp_s_170_0, :text
      add_column :sp_bsbs, :sp_s_170_1, :text
      add_column :sp_bsbs, :sp_s_170_2, :text
      add_column :sp_bsbs, :sp_s_170_3, :text
      add_column :sp_bsbs, :sp_s_170_4, :text
      add_column :sp_bsbs, :sp_s_170_5, :text
      add_column :sp_bsbs, :sp_s_170_6, :text
      add_column :sp_bsbs, :sp_s_170_7, :text
      add_column :sp_bsbs, :sp_s_170_8, :text
      add_column :sp_bsbs, :sp_s_170_9, :text
      add_column :sp_bsbs, :sp_s_171_0, :text
      add_column :sp_bsbs, :sp_s_171_1, :text
      add_column :sp_bsbs, :sp_s_171_2, :text
      add_column :sp_bsbs, :sp_s_171_3, :text
      add_column :sp_bsbs, :sp_s_171_4, :text
      add_column :sp_bsbs, :sp_s_171_5, :text
      add_column :sp_bsbs, :sp_s_171_6, :text
      add_column :sp_bsbs, :sp_s_171_7, :text
      add_column :sp_bsbs, :sp_s_171_8, :text
      add_column :sp_bsbs, :sp_s_171_9, :text
      add_column :sp_bsbs, :sp_s_172_0, :text
      add_column :sp_bsbs, :sp_s_172_1, :text
      add_column :sp_bsbs, :sp_s_172_2, :text
      add_column :sp_bsbs, :sp_s_172_3, :text
      add_column :sp_bsbs, :sp_s_172_4, :text
      add_column :sp_bsbs, :sp_s_172_5, :text
      add_column :sp_bsbs, :sp_s_172_6, :text
      add_column :sp_bsbs, :sp_s_172_7, :text
      add_column :sp_bsbs, :sp_s_172_8, :text
      add_column :sp_bsbs, :sp_s_172_9, :text
      add_column :sp_bsbs, :sp_s_173_0, :text
      add_column :sp_bsbs, :sp_s_173_1, :text
      add_column :sp_bsbs, :sp_s_173_2, :text
      add_column :sp_bsbs, :sp_s_173_3, :text
      add_column :sp_bsbs, :sp_s_173_4, :text
      add_column :sp_bsbs, :sp_s_173_5, :text
      add_column :sp_bsbs, :sp_s_173_6, :text
      add_column :sp_bsbs, :sp_s_173_7, :text
      add_column :sp_bsbs, :sp_s_173_8, :text
      add_column :sp_bsbs, :sp_s_173_9, :text
      add_column :sp_bsbs, :sp_s_174_0, :text
      add_column :sp_bsbs, :sp_s_174_1, :text
      add_column :sp_bsbs, :sp_s_174_2, :text
      add_column :sp_bsbs, :sp_s_174_3, :text
      add_column :sp_bsbs, :sp_s_174_4, :text
      add_column :sp_bsbs, :sp_s_174_5, :text
      add_column :sp_bsbs, :sp_s_174_6, :text
      add_column :sp_bsbs, :sp_s_174_7, :text
      add_column :sp_bsbs, :sp_s_174_8, :text
      add_column :sp_bsbs, :sp_s_174_9, :text
      add_column :sp_bsbs, :sp_s_175_0, :text
      add_column :sp_bsbs, :sp_s_175_1, :text
      add_column :sp_bsbs, :sp_s_175_2, :text
      add_column :sp_bsbs, :sp_s_175_3, :text
      add_column :sp_bsbs, :sp_s_175_4, :text
      add_column :sp_bsbs, :sp_s_175_5, :text
      add_column :sp_bsbs, :sp_s_175_6, :text
      add_column :sp_bsbs, :sp_s_175_7, :text
      add_column :sp_bsbs, :sp_s_175_8, :text
      add_column :sp_bsbs, :sp_s_175_9, :text
      add_column :sp_bsbs, :sp_s_176_0, :text
      add_column :sp_bsbs, :sp_s_176_1, :text
      add_column :sp_bsbs, :sp_s_176_2, :text
      add_column :sp_bsbs, :sp_s_176_3, :text
      add_column :sp_bsbs, :sp_s_176_4, :text
      add_column :sp_bsbs, :sp_s_176_5, :text
      add_column :sp_bsbs, :sp_s_176_6, :text
      add_column :sp_bsbs, :sp_s_176_7, :text
      add_column :sp_bsbs, :sp_s_176_8, :text
      add_column :sp_bsbs, :sp_s_176_9, :text
      add_column :sp_bsbs, :sp_s_177_0, :text
      add_column :sp_bsbs, :sp_s_177_1, :text
      add_column :sp_bsbs, :sp_s_177_2, :text
      add_column :sp_bsbs, :sp_s_177_3, :text
      add_column :sp_bsbs, :sp_s_177_4, :text
      add_column :sp_bsbs, :sp_s_177_5, :text
      add_column :sp_bsbs, :sp_s_177_6, :text
      add_column :sp_bsbs, :sp_s_177_7, :text
      add_column :sp_bsbs, :sp_s_177_8, :text
      add_column :sp_bsbs, :sp_s_177_9, :text
      add_column :sp_bsbs, :sp_s_178_0, :text
      add_column :sp_bsbs, :sp_s_178_1, :text
      add_column :sp_bsbs, :sp_s_178_2, :text
      add_column :sp_bsbs, :sp_s_178_3, :text
      add_column :sp_bsbs, :sp_s_178_4, :text
      add_column :sp_bsbs, :sp_s_178_5, :text
      add_column :sp_bsbs, :sp_s_178_6, :text
      add_column :sp_bsbs, :sp_s_178_7, :text
      add_column :sp_bsbs, :sp_s_178_8, :text
      add_column :sp_bsbs, :sp_s_178_9, :text
      add_column :sp_bsbs, :sp_s_179_0, :text
      add_column :sp_bsbs, :sp_s_179_1, :text
      add_column :sp_bsbs, :sp_s_179_2, :text
      add_column :sp_bsbs, :sp_s_179_3, :text
      add_column :sp_bsbs, :sp_s_179_4, :text
      add_column :sp_bsbs, :sp_s_179_5, :text
      add_column :sp_bsbs, :sp_s_179_6, :text
      add_column :sp_bsbs, :sp_s_179_7, :text
      add_column :sp_bsbs, :sp_s_179_8, :text
      add_column :sp_bsbs, :sp_s_179_9, :text
  end
end
