class RemoveFromSpBsbs110 < ActiveRecord::Migration
  def up
      remove_column :sp_bsbs, :sp_s_110_0
      remove_column :sp_bsbs, :sp_s_110_1
      remove_column :sp_bsbs, :sp_s_110_2
      remove_column :sp_bsbs, :sp_s_110_3
      remove_column :sp_bsbs, :sp_s_110_4
      remove_column :sp_bsbs, :sp_s_110_5
      remove_column :sp_bsbs, :sp_s_110_6
      remove_column :sp_bsbs, :sp_s_110_7
      remove_column :sp_bsbs, :sp_s_110_8
      remove_column :sp_bsbs, :sp_s_110_9
      remove_column :sp_bsbs, :sp_s_111_0
      remove_column :sp_bsbs, :sp_s_111_1
      remove_column :sp_bsbs, :sp_s_111_2
      remove_column :sp_bsbs, :sp_s_111_3
      remove_column :sp_bsbs, :sp_s_111_4
      remove_column :sp_bsbs, :sp_s_111_5
      remove_column :sp_bsbs, :sp_s_111_6
      remove_column :sp_bsbs, :sp_s_111_7
      remove_column :sp_bsbs, :sp_s_111_8
      remove_column :sp_bsbs, :sp_s_111_9
      remove_column :sp_bsbs, :sp_s_112_0
      remove_column :sp_bsbs, :sp_s_112_1
      remove_column :sp_bsbs, :sp_s_112_2
      remove_column :sp_bsbs, :sp_s_112_3
      remove_column :sp_bsbs, :sp_s_112_4
      remove_column :sp_bsbs, :sp_s_112_5
      remove_column :sp_bsbs, :sp_s_112_6
      remove_column :sp_bsbs, :sp_s_112_7
      remove_column :sp_bsbs, :sp_s_112_8
      remove_column :sp_bsbs, :sp_s_112_9
      remove_column :sp_bsbs, :sp_s_113_0
      remove_column :sp_bsbs, :sp_s_113_1
      remove_column :sp_bsbs, :sp_s_113_2
      remove_column :sp_bsbs, :sp_s_113_3
      remove_column :sp_bsbs, :sp_s_113_4
      remove_column :sp_bsbs, :sp_s_113_5
      remove_column :sp_bsbs, :sp_s_113_6
      remove_column :sp_bsbs, :sp_s_113_7
      remove_column :sp_bsbs, :sp_s_113_8
      remove_column :sp_bsbs, :sp_s_113_9
      remove_column :sp_bsbs, :sp_s_114_0
      remove_column :sp_bsbs, :sp_s_114_1
      remove_column :sp_bsbs, :sp_s_114_2
      remove_column :sp_bsbs, :sp_s_114_3
      remove_column :sp_bsbs, :sp_s_114_4
      remove_column :sp_bsbs, :sp_s_114_5
      remove_column :sp_bsbs, :sp_s_114_6
      remove_column :sp_bsbs, :sp_s_114_7
      remove_column :sp_bsbs, :sp_s_114_8
      remove_column :sp_bsbs, :sp_s_114_9
      remove_column :sp_bsbs, :sp_s_115_0
      remove_column :sp_bsbs, :sp_s_115_1
      remove_column :sp_bsbs, :sp_s_115_2
      remove_column :sp_bsbs, :sp_s_115_3
      remove_column :sp_bsbs, :sp_s_115_4
      remove_column :sp_bsbs, :sp_s_115_5
      remove_column :sp_bsbs, :sp_s_115_6
      remove_column :sp_bsbs, :sp_s_115_7
      remove_column :sp_bsbs, :sp_s_115_8
      remove_column :sp_bsbs, :sp_s_115_9
      remove_column :sp_bsbs, :sp_s_116_0
      remove_column :sp_bsbs, :sp_s_116_1
      remove_column :sp_bsbs, :sp_s_116_2
      remove_column :sp_bsbs, :sp_s_116_3
      remove_column :sp_bsbs, :sp_s_116_4
      remove_column :sp_bsbs, :sp_s_116_5
      remove_column :sp_bsbs, :sp_s_116_6
      remove_column :sp_bsbs, :sp_s_116_7
      remove_column :sp_bsbs, :sp_s_116_8
      remove_column :sp_bsbs, :sp_s_116_9
      remove_column :sp_bsbs, :sp_s_117_0
      remove_column :sp_bsbs, :sp_s_117_1
      remove_column :sp_bsbs, :sp_s_117_2
      remove_column :sp_bsbs, :sp_s_117_3
      remove_column :sp_bsbs, :sp_s_117_4
      remove_column :sp_bsbs, :sp_s_117_5
      remove_column :sp_bsbs, :sp_s_117_6
      remove_column :sp_bsbs, :sp_s_117_7
      remove_column :sp_bsbs, :sp_s_117_8
      remove_column :sp_bsbs, :sp_s_117_9
      remove_column :sp_bsbs, :sp_s_118_0
      remove_column :sp_bsbs, :sp_s_118_1
      remove_column :sp_bsbs, :sp_s_118_2
      remove_column :sp_bsbs, :sp_s_118_3
      remove_column :sp_bsbs, :sp_s_118_4
      remove_column :sp_bsbs, :sp_s_118_5
      remove_column :sp_bsbs, :sp_s_118_6
      remove_column :sp_bsbs, :sp_s_118_7
      remove_column :sp_bsbs, :sp_s_118_8
      remove_column :sp_bsbs, :sp_s_118_9
      remove_column :sp_bsbs, :sp_s_119_0
      remove_column :sp_bsbs, :sp_s_119_1
      remove_column :sp_bsbs, :sp_s_119_2
      remove_column :sp_bsbs, :sp_s_119_3
      remove_column :sp_bsbs, :sp_s_119_4
      remove_column :sp_bsbs, :sp_s_119_5
      remove_column :sp_bsbs, :sp_s_119_6
      remove_column :sp_bsbs, :sp_s_119_7
      remove_column :sp_bsbs, :sp_s_119_8
      remove_column :sp_bsbs, :sp_s_119_9
      remove_column :sp_bsbs, :sp_s_120_0
      remove_column :sp_bsbs, :sp_s_120_1
      remove_column :sp_bsbs, :sp_s_120_2
      remove_column :sp_bsbs, :sp_s_120_3
      remove_column :sp_bsbs, :sp_s_120_4
      remove_column :sp_bsbs, :sp_s_120_5
      remove_column :sp_bsbs, :sp_s_120_6
      remove_column :sp_bsbs, :sp_s_120_7
      remove_column :sp_bsbs, :sp_s_120_8
      remove_column :sp_bsbs, :sp_s_120_9
      remove_column :sp_bsbs, :sp_s_121_0
      remove_column :sp_bsbs, :sp_s_121_1
      remove_column :sp_bsbs, :sp_s_121_2
      remove_column :sp_bsbs, :sp_s_121_3
      remove_column :sp_bsbs, :sp_s_121_4
      remove_column :sp_bsbs, :sp_s_121_5
      remove_column :sp_bsbs, :sp_s_121_6
      remove_column :sp_bsbs, :sp_s_121_7
      remove_column :sp_bsbs, :sp_s_121_8
      remove_column :sp_bsbs, :sp_s_121_9
      remove_column :sp_bsbs, :sp_s_122_0
      remove_column :sp_bsbs, :sp_s_122_1
      remove_column :sp_bsbs, :sp_s_122_2
      remove_column :sp_bsbs, :sp_s_122_3
      remove_column :sp_bsbs, :sp_s_122_4
      remove_column :sp_bsbs, :sp_s_122_5
      remove_column :sp_bsbs, :sp_s_122_6
      remove_column :sp_bsbs, :sp_s_122_7
      remove_column :sp_bsbs, :sp_s_122_8
      remove_column :sp_bsbs, :sp_s_122_9
      remove_column :sp_bsbs, :sp_s_123_0
      remove_column :sp_bsbs, :sp_s_123_1
      remove_column :sp_bsbs, :sp_s_123_2
      remove_column :sp_bsbs, :sp_s_123_3
      remove_column :sp_bsbs, :sp_s_123_4
      remove_column :sp_bsbs, :sp_s_123_5
      remove_column :sp_bsbs, :sp_s_123_6
      remove_column :sp_bsbs, :sp_s_123_7
      remove_column :sp_bsbs, :sp_s_123_8
      remove_column :sp_bsbs, :sp_s_123_9
      remove_column :sp_bsbs, :sp_s_124_0
      remove_column :sp_bsbs, :sp_s_124_1
      remove_column :sp_bsbs, :sp_s_124_2
      remove_column :sp_bsbs, :sp_s_124_3
      remove_column :sp_bsbs, :sp_s_124_4
      remove_column :sp_bsbs, :sp_s_124_5
      remove_column :sp_bsbs, :sp_s_124_6
      remove_column :sp_bsbs, :sp_s_124_7
      remove_column :sp_bsbs, :sp_s_124_8
      remove_column :sp_bsbs, :sp_s_124_9
      remove_column :sp_bsbs, :sp_s_125_0
      remove_column :sp_bsbs, :sp_s_125_1
      remove_column :sp_bsbs, :sp_s_125_2
      remove_column :sp_bsbs, :sp_s_125_3
      remove_column :sp_bsbs, :sp_s_125_4
      remove_column :sp_bsbs, :sp_s_125_5
      remove_column :sp_bsbs, :sp_s_125_6
      remove_column :sp_bsbs, :sp_s_125_7
      remove_column :sp_bsbs, :sp_s_125_8
      remove_column :sp_bsbs, :sp_s_125_9
      remove_column :sp_bsbs, :sp_s_126_0
      remove_column :sp_bsbs, :sp_s_126_1
      remove_column :sp_bsbs, :sp_s_126_2
      remove_column :sp_bsbs, :sp_s_126_3
      remove_column :sp_bsbs, :sp_s_126_4
      remove_column :sp_bsbs, :sp_s_126_5
      remove_column :sp_bsbs, :sp_s_126_6
      remove_column :sp_bsbs, :sp_s_126_7
      remove_column :sp_bsbs, :sp_s_126_8
      remove_column :sp_bsbs, :sp_s_126_9
      remove_column :sp_bsbs, :sp_s_127_0
      remove_column :sp_bsbs, :sp_s_127_1
      remove_column :sp_bsbs, :sp_s_127_2
      remove_column :sp_bsbs, :sp_s_127_3
      remove_column :sp_bsbs, :sp_s_127_4
      remove_column :sp_bsbs, :sp_s_127_5
      remove_column :sp_bsbs, :sp_s_127_6
      remove_column :sp_bsbs, :sp_s_127_7
      remove_column :sp_bsbs, :sp_s_127_8
      remove_column :sp_bsbs, :sp_s_127_9
      remove_column :sp_bsbs, :sp_s_128_0
      remove_column :sp_bsbs, :sp_s_128_1
      remove_column :sp_bsbs, :sp_s_128_2
      remove_column :sp_bsbs, :sp_s_128_3
      remove_column :sp_bsbs, :sp_s_128_4
      remove_column :sp_bsbs, :sp_s_128_5
      remove_column :sp_bsbs, :sp_s_128_6
      remove_column :sp_bsbs, :sp_s_128_7
      remove_column :sp_bsbs, :sp_s_128_8
      remove_column :sp_bsbs, :sp_s_128_9
      remove_column :sp_bsbs, :sp_s_129_0
      remove_column :sp_bsbs, :sp_s_129_1
      remove_column :sp_bsbs, :sp_s_129_2
      remove_column :sp_bsbs, :sp_s_129_3
      remove_column :sp_bsbs, :sp_s_129_4
      remove_column :sp_bsbs, :sp_s_129_5
      remove_column :sp_bsbs, :sp_s_129_6
      remove_column :sp_bsbs, :sp_s_129_7
      remove_column :sp_bsbs, :sp_s_129_8
      remove_column :sp_bsbs, :sp_s_129_9
      remove_column :sp_bsbs, :sp_s_130_0
      remove_column :sp_bsbs, :sp_s_130_1
      remove_column :sp_bsbs, :sp_s_130_2
      remove_column :sp_bsbs, :sp_s_130_3
      remove_column :sp_bsbs, :sp_s_130_4
      remove_column :sp_bsbs, :sp_s_130_5
      remove_column :sp_bsbs, :sp_s_130_6
      remove_column :sp_bsbs, :sp_s_130_7
      remove_column :sp_bsbs, :sp_s_130_8
      remove_column :sp_bsbs, :sp_s_130_9
      remove_column :sp_bsbs, :sp_s_131_0
      remove_column :sp_bsbs, :sp_s_131_1
      remove_column :sp_bsbs, :sp_s_131_2
      remove_column :sp_bsbs, :sp_s_131_3
      remove_column :sp_bsbs, :sp_s_131_4
      remove_column :sp_bsbs, :sp_s_131_5
      remove_column :sp_bsbs, :sp_s_131_6
      remove_column :sp_bsbs, :sp_s_131_7
      remove_column :sp_bsbs, :sp_s_131_8
      remove_column :sp_bsbs, :sp_s_131_9
      remove_column :sp_bsbs, :sp_s_132_0
      remove_column :sp_bsbs, :sp_s_132_1
      remove_column :sp_bsbs, :sp_s_132_2
      remove_column :sp_bsbs, :sp_s_132_3
      remove_column :sp_bsbs, :sp_s_132_4
      remove_column :sp_bsbs, :sp_s_132_5
      remove_column :sp_bsbs, :sp_s_132_6
      remove_column :sp_bsbs, :sp_s_132_7
      remove_column :sp_bsbs, :sp_s_132_8
      remove_column :sp_bsbs, :sp_s_132_9
      remove_column :sp_bsbs, :sp_s_133_0
      remove_column :sp_bsbs, :sp_s_133_1
      remove_column :sp_bsbs, :sp_s_133_2
      remove_column :sp_bsbs, :sp_s_133_3
      remove_column :sp_bsbs, :sp_s_133_4
      remove_column :sp_bsbs, :sp_s_133_5
      remove_column :sp_bsbs, :sp_s_133_6
      remove_column :sp_bsbs, :sp_s_133_7
      remove_column :sp_bsbs, :sp_s_133_8
      remove_column :sp_bsbs, :sp_s_133_9
      remove_column :sp_bsbs, :sp_s_134_0
      remove_column :sp_bsbs, :sp_s_134_1
      remove_column :sp_bsbs, :sp_s_134_2
      remove_column :sp_bsbs, :sp_s_134_3
      remove_column :sp_bsbs, :sp_s_134_4
      remove_column :sp_bsbs, :sp_s_134_5
      remove_column :sp_bsbs, :sp_s_134_6
      remove_column :sp_bsbs, :sp_s_134_7
      remove_column :sp_bsbs, :sp_s_134_8
      remove_column :sp_bsbs, :sp_s_134_9
      remove_column :sp_bsbs, :sp_s_135_0
      remove_column :sp_bsbs, :sp_s_135_1
      remove_column :sp_bsbs, :sp_s_135_2
      remove_column :sp_bsbs, :sp_s_135_3
      remove_column :sp_bsbs, :sp_s_135_4
      remove_column :sp_bsbs, :sp_s_135_5
      remove_column :sp_bsbs, :sp_s_135_6
      remove_column :sp_bsbs, :sp_s_135_7
      remove_column :sp_bsbs, :sp_s_135_8
      remove_column :sp_bsbs, :sp_s_135_9
      remove_column :sp_bsbs, :sp_s_136_0
      remove_column :sp_bsbs, :sp_s_136_1
      remove_column :sp_bsbs, :sp_s_136_2
      remove_column :sp_bsbs, :sp_s_136_3
      remove_column :sp_bsbs, :sp_s_136_4
      remove_column :sp_bsbs, :sp_s_136_5
      remove_column :sp_bsbs, :sp_s_136_6
      remove_column :sp_bsbs, :sp_s_136_7
      remove_column :sp_bsbs, :sp_s_136_8
      remove_column :sp_bsbs, :sp_s_136_9
      remove_column :sp_bsbs, :sp_s_137_0
      remove_column :sp_bsbs, :sp_s_137_1
      remove_column :sp_bsbs, :sp_s_137_2
      remove_column :sp_bsbs, :sp_s_137_3
      remove_column :sp_bsbs, :sp_s_137_4
      remove_column :sp_bsbs, :sp_s_137_5
      remove_column :sp_bsbs, :sp_s_137_6
      remove_column :sp_bsbs, :sp_s_137_7
      remove_column :sp_bsbs, :sp_s_137_8
      remove_column :sp_bsbs, :sp_s_137_9
      remove_column :sp_bsbs, :sp_s_138_0
      remove_column :sp_bsbs, :sp_s_138_1
      remove_column :sp_bsbs, :sp_s_138_2
      remove_column :sp_bsbs, :sp_s_138_3
      remove_column :sp_bsbs, :sp_s_138_4
      remove_column :sp_bsbs, :sp_s_138_5
      remove_column :sp_bsbs, :sp_s_138_6
      remove_column :sp_bsbs, :sp_s_138_7
      remove_column :sp_bsbs, :sp_s_138_8
      remove_column :sp_bsbs, :sp_s_138_9
      remove_column :sp_bsbs, :sp_s_139_0
      remove_column :sp_bsbs, :sp_s_139_1
      remove_column :sp_bsbs, :sp_s_139_2
      remove_column :sp_bsbs, :sp_s_139_3
      remove_column :sp_bsbs, :sp_s_139_4
      remove_column :sp_bsbs, :sp_s_139_5
      remove_column :sp_bsbs, :sp_s_139_6
      remove_column :sp_bsbs, :sp_s_139_7
      remove_column :sp_bsbs, :sp_s_139_8
      remove_column :sp_bsbs, :sp_s_139_9
  end

  def down
  end
end
