class RemoveFromSpBsb140 < ActiveRecord::Migration
  def up
      remove_column :sp_bsbs, :sp_s_141_1
      remove_column :sp_bsbs, :sp_s_141_2
      remove_column :sp_bsbs, :sp_s_141_3
      remove_column :sp_bsbs, :sp_s_141_4
      remove_column :sp_bsbs, :sp_s_141_5
      remove_column :sp_bsbs, :sp_s_141_6
      remove_column :sp_bsbs, :sp_s_141_7
      remove_column :sp_bsbs, :sp_s_141_8
      remove_column :sp_bsbs, :sp_s_141_9
      remove_column :sp_bsbs, :sp_s_142_0
      remove_column :sp_bsbs, :sp_s_142_1
      remove_column :sp_bsbs, :sp_s_142_2
      remove_column :sp_bsbs, :sp_s_142_3
      remove_column :sp_bsbs, :sp_s_142_4
      remove_column :sp_bsbs, :sp_s_142_5
      remove_column :sp_bsbs, :sp_s_142_6
      remove_column :sp_bsbs, :sp_s_142_7
      remove_column :sp_bsbs, :sp_s_142_8
      remove_column :sp_bsbs, :sp_s_142_9
      remove_column :sp_bsbs, :sp_s_143_0
      remove_column :sp_bsbs, :sp_s_143_1
      remove_column :sp_bsbs, :sp_s_143_2
      remove_column :sp_bsbs, :sp_s_143_3
      remove_column :sp_bsbs, :sp_s_143_4
      remove_column :sp_bsbs, :sp_s_143_5
      remove_column :sp_bsbs, :sp_s_143_6
      remove_column :sp_bsbs, :sp_s_143_7
      remove_column :sp_bsbs, :sp_s_143_8
      remove_column :sp_bsbs, :sp_s_143_9
      remove_column :sp_bsbs, :sp_s_144_0
      remove_column :sp_bsbs, :sp_s_144_1
      remove_column :sp_bsbs, :sp_s_144_2
      remove_column :sp_bsbs, :sp_s_144_3
      remove_column :sp_bsbs, :sp_s_144_4
      remove_column :sp_bsbs, :sp_s_144_5
      remove_column :sp_bsbs, :sp_s_144_6
      remove_column :sp_bsbs, :sp_s_144_7
      remove_column :sp_bsbs, :sp_s_144_8
      remove_column :sp_bsbs, :sp_s_144_9
      remove_column :sp_bsbs, :sp_s_145_0
      remove_column :sp_bsbs, :sp_s_145_1
      remove_column :sp_bsbs, :sp_s_145_2
      remove_column :sp_bsbs, :sp_s_145_3
      remove_column :sp_bsbs, :sp_s_145_4
      remove_column :sp_bsbs, :sp_s_145_5
      remove_column :sp_bsbs, :sp_s_145_6
      remove_column :sp_bsbs, :sp_s_145_7
      remove_column :sp_bsbs, :sp_s_145_8
      remove_column :sp_bsbs, :sp_s_145_9
      remove_column :sp_bsbs, :sp_s_146_0
      remove_column :sp_bsbs, :sp_s_146_1
      remove_column :sp_bsbs, :sp_s_146_2
      remove_column :sp_bsbs, :sp_s_146_3
      remove_column :sp_bsbs, :sp_s_146_4
      remove_column :sp_bsbs, :sp_s_146_5
      remove_column :sp_bsbs, :sp_s_146_6
      remove_column :sp_bsbs, :sp_s_146_7
      remove_column :sp_bsbs, :sp_s_146_8
      remove_column :sp_bsbs, :sp_s_146_9
      remove_column :sp_bsbs, :sp_s_147_0
      remove_column :sp_bsbs, :sp_s_147_1
      remove_column :sp_bsbs, :sp_s_147_2
      remove_column :sp_bsbs, :sp_s_147_3
      remove_column :sp_bsbs, :sp_s_147_4
      remove_column :sp_bsbs, :sp_s_147_5
      remove_column :sp_bsbs, :sp_s_147_6
      remove_column :sp_bsbs, :sp_s_147_7
      remove_column :sp_bsbs, :sp_s_147_8
      remove_column :sp_bsbs, :sp_s_147_9
      remove_column :sp_bsbs, :sp_s_148_0
      remove_column :sp_bsbs, :sp_s_148_1
      remove_column :sp_bsbs, :sp_s_148_2
      remove_column :sp_bsbs, :sp_s_148_3
      remove_column :sp_bsbs, :sp_s_148_4
      remove_column :sp_bsbs, :sp_s_148_5
      remove_column :sp_bsbs, :sp_s_148_6
      remove_column :sp_bsbs, :sp_s_148_7
      remove_column :sp_bsbs, :sp_s_148_8
      remove_column :sp_bsbs, :sp_s_148_9
      remove_column :sp_bsbs, :sp_s_149_0
      remove_column :sp_bsbs, :sp_s_149_1
      remove_column :sp_bsbs, :sp_s_149_2
      remove_column :sp_bsbs, :sp_s_149_3
      remove_column :sp_bsbs, :sp_s_149_4
      remove_column :sp_bsbs, :sp_s_149_5
      remove_column :sp_bsbs, :sp_s_149_6
      remove_column :sp_bsbs, :sp_s_149_7
      remove_column :sp_bsbs, :sp_s_149_8
      remove_column :sp_bsbs, :sp_s_149_9
      remove_column :sp_bsbs, :sp_s_150_0
      remove_column :sp_bsbs, :sp_s_150_1
      remove_column :sp_bsbs, :sp_s_150_2
      remove_column :sp_bsbs, :sp_s_150_3
      remove_column :sp_bsbs, :sp_s_150_4
      remove_column :sp_bsbs, :sp_s_150_5
      remove_column :sp_bsbs, :sp_s_150_6
      remove_column :sp_bsbs, :sp_s_150_7
      remove_column :sp_bsbs, :sp_s_150_8
      remove_column :sp_bsbs, :sp_s_150_9
      remove_column :sp_bsbs, :sp_s_151_0
      remove_column :sp_bsbs, :sp_s_151_1
      remove_column :sp_bsbs, :sp_s_151_2
      remove_column :sp_bsbs, :sp_s_151_3
      remove_column :sp_bsbs, :sp_s_151_4
      remove_column :sp_bsbs, :sp_s_151_5
      remove_column :sp_bsbs, :sp_s_151_6
      remove_column :sp_bsbs, :sp_s_151_7
      remove_column :sp_bsbs, :sp_s_151_8
      remove_column :sp_bsbs, :sp_s_151_9
      remove_column :sp_bsbs, :sp_s_152_0
      remove_column :sp_bsbs, :sp_s_152_1
      remove_column :sp_bsbs, :sp_s_152_2
      remove_column :sp_bsbs, :sp_s_152_3
      remove_column :sp_bsbs, :sp_s_152_4
      remove_column :sp_bsbs, :sp_s_152_5
      remove_column :sp_bsbs, :sp_s_152_6
      remove_column :sp_bsbs, :sp_s_152_7
      remove_column :sp_bsbs, :sp_s_152_8
      remove_column :sp_bsbs, :sp_s_152_9
      remove_column :sp_bsbs, :sp_s_153_0
      remove_column :sp_bsbs, :sp_s_153_1
      remove_column :sp_bsbs, :sp_s_153_2
      remove_column :sp_bsbs, :sp_s_153_3
      remove_column :sp_bsbs, :sp_s_153_4
      remove_column :sp_bsbs, :sp_s_153_5
      remove_column :sp_bsbs, :sp_s_153_6
      remove_column :sp_bsbs, :sp_s_153_7
      remove_column :sp_bsbs, :sp_s_153_8
      remove_column :sp_bsbs, :sp_s_153_9
      remove_column :sp_bsbs, :sp_s_154_0
      remove_column :sp_bsbs, :sp_s_154_1
      remove_column :sp_bsbs, :sp_s_154_2
      remove_column :sp_bsbs, :sp_s_154_3
      remove_column :sp_bsbs, :sp_s_154_4
      remove_column :sp_bsbs, :sp_s_154_5
      remove_column :sp_bsbs, :sp_s_154_6
      remove_column :sp_bsbs, :sp_s_154_7
      remove_column :sp_bsbs, :sp_s_154_8
      remove_column :sp_bsbs, :sp_s_154_9
      remove_column :sp_bsbs, :sp_s_155_0
      remove_column :sp_bsbs, :sp_s_155_1
      remove_column :sp_bsbs, :sp_s_155_2
      remove_column :sp_bsbs, :sp_s_155_3
      remove_column :sp_bsbs, :sp_s_155_4
      remove_column :sp_bsbs, :sp_s_155_5
      remove_column :sp_bsbs, :sp_s_155_6
      remove_column :sp_bsbs, :sp_s_155_7
      remove_column :sp_bsbs, :sp_s_155_8
      remove_column :sp_bsbs, :sp_s_155_9
      remove_column :sp_bsbs, :sp_s_156_0
      remove_column :sp_bsbs, :sp_s_156_1
      remove_column :sp_bsbs, :sp_s_156_2
      remove_column :sp_bsbs, :sp_s_156_3
      remove_column :sp_bsbs, :sp_s_156_4
      remove_column :sp_bsbs, :sp_s_156_5
      remove_column :sp_bsbs, :sp_s_156_6
      remove_column :sp_bsbs, :sp_s_156_7
      remove_column :sp_bsbs, :sp_s_156_8
      remove_column :sp_bsbs, :sp_s_156_9
      remove_column :sp_bsbs, :sp_s_157_0
      remove_column :sp_bsbs, :sp_s_157_1
      remove_column :sp_bsbs, :sp_s_157_2
      remove_column :sp_bsbs, :sp_s_157_3
      remove_column :sp_bsbs, :sp_s_157_4
      remove_column :sp_bsbs, :sp_s_157_5
      remove_column :sp_bsbs, :sp_s_157_6
      remove_column :sp_bsbs, :sp_s_157_7
      remove_column :sp_bsbs, :sp_s_157_8
      remove_column :sp_bsbs, :sp_s_157_9
      remove_column :sp_bsbs, :sp_s_158_0
      remove_column :sp_bsbs, :sp_s_158_1
      remove_column :sp_bsbs, :sp_s_158_2
      remove_column :sp_bsbs, :sp_s_158_3
      remove_column :sp_bsbs, :sp_s_158_4
      remove_column :sp_bsbs, :sp_s_158_5
      remove_column :sp_bsbs, :sp_s_158_6
      remove_column :sp_bsbs, :sp_s_158_7
      remove_column :sp_bsbs, :sp_s_158_8
      remove_column :sp_bsbs, :sp_s_158_9
      remove_column :sp_bsbs, :sp_s_159_0
      remove_column :sp_bsbs, :sp_s_159_1
      remove_column :sp_bsbs, :sp_s_159_2
      remove_column :sp_bsbs, :sp_s_159_3
      remove_column :sp_bsbs, :sp_s_159_4
      remove_column :sp_bsbs, :sp_s_159_5
      remove_column :sp_bsbs, :sp_s_159_6
      remove_column :sp_bsbs, :sp_s_159_7
      remove_column :sp_bsbs, :sp_s_159_8
      remove_column :sp_bsbs, :sp_s_159_9
      remove_column :sp_bsbs, :sp_s_160_0
      remove_column :sp_bsbs, :sp_s_160_1
      remove_column :sp_bsbs, :sp_s_160_2
      remove_column :sp_bsbs, :sp_s_160_3
      remove_column :sp_bsbs, :sp_s_160_4
      remove_column :sp_bsbs, :sp_s_160_5
      remove_column :sp_bsbs, :sp_s_160_6
      remove_column :sp_bsbs, :sp_s_160_7
      remove_column :sp_bsbs, :sp_s_160_8
      remove_column :sp_bsbs, :sp_s_160_9
      remove_column :sp_bsbs, :sp_s_161_0
      remove_column :sp_bsbs, :sp_s_161_1
      remove_column :sp_bsbs, :sp_s_161_2
      remove_column :sp_bsbs, :sp_s_161_3
      remove_column :sp_bsbs, :sp_s_161_4
      remove_column :sp_bsbs, :sp_s_161_5
      remove_column :sp_bsbs, :sp_s_161_6
      remove_column :sp_bsbs, :sp_s_161_7
      remove_column :sp_bsbs, :sp_s_161_8
      remove_column :sp_bsbs, :sp_s_161_9
      remove_column :sp_bsbs, :sp_s_162_0
      remove_column :sp_bsbs, :sp_s_162_1
      remove_column :sp_bsbs, :sp_s_162_2
      remove_column :sp_bsbs, :sp_s_162_3
      remove_column :sp_bsbs, :sp_s_162_4
      remove_column :sp_bsbs, :sp_s_162_5
      remove_column :sp_bsbs, :sp_s_162_6
      remove_column :sp_bsbs, :sp_s_162_7
      remove_column :sp_bsbs, :sp_s_162_8
      remove_column :sp_bsbs, :sp_s_162_9
      remove_column :sp_bsbs, :sp_s_163_0
      remove_column :sp_bsbs, :sp_s_163_1
      remove_column :sp_bsbs, :sp_s_163_2
      remove_column :sp_bsbs, :sp_s_163_3
      remove_column :sp_bsbs, :sp_s_163_4
      remove_column :sp_bsbs, :sp_s_163_5
      remove_column :sp_bsbs, :sp_s_163_6
      remove_column :sp_bsbs, :sp_s_163_7
      remove_column :sp_bsbs, :sp_s_163_8
      remove_column :sp_bsbs, :sp_s_163_9
      remove_column :sp_bsbs, :sp_s_164_0
      remove_column :sp_bsbs, :sp_s_164_1
      remove_column :sp_bsbs, :sp_s_164_2
      remove_column :sp_bsbs, :sp_s_164_3
      remove_column :sp_bsbs, :sp_s_164_4
      remove_column :sp_bsbs, :sp_s_164_5
      remove_column :sp_bsbs, :sp_s_164_6
      remove_column :sp_bsbs, :sp_s_164_7
      remove_column :sp_bsbs, :sp_s_164_8
      remove_column :sp_bsbs, :sp_s_164_9
      remove_column :sp_bsbs, :sp_s_165_0
      remove_column :sp_bsbs, :sp_s_165_1
      remove_column :sp_bsbs, :sp_s_165_2
      remove_column :sp_bsbs, :sp_s_165_3
      remove_column :sp_bsbs, :sp_s_165_4
      remove_column :sp_bsbs, :sp_s_165_5
      remove_column :sp_bsbs, :sp_s_165_6
      remove_column :sp_bsbs, :sp_s_165_7
      remove_column :sp_bsbs, :sp_s_165_8
      remove_column :sp_bsbs, :sp_s_165_9
      remove_column :sp_bsbs, :sp_s_166_0
      remove_column :sp_bsbs, :sp_s_166_1
      remove_column :sp_bsbs, :sp_s_166_2
      remove_column :sp_bsbs, :sp_s_166_3
      remove_column :sp_bsbs, :sp_s_166_4
      remove_column :sp_bsbs, :sp_s_166_5
      remove_column :sp_bsbs, :sp_s_166_6
      remove_column :sp_bsbs, :sp_s_166_7
      remove_column :sp_bsbs, :sp_s_166_8
      remove_column :sp_bsbs, :sp_s_166_9
      remove_column :sp_bsbs, :sp_s_167_0
      remove_column :sp_bsbs, :sp_s_167_1
      remove_column :sp_bsbs, :sp_s_167_2
      remove_column :sp_bsbs, :sp_s_167_3
      remove_column :sp_bsbs, :sp_s_167_4
      remove_column :sp_bsbs, :sp_s_167_5
      remove_column :sp_bsbs, :sp_s_167_6
      remove_column :sp_bsbs, :sp_s_167_7
      remove_column :sp_bsbs, :sp_s_167_8
      remove_column :sp_bsbs, :sp_s_167_9
      remove_column :sp_bsbs, :sp_s_168_0
      remove_column :sp_bsbs, :sp_s_168_1
      remove_column :sp_bsbs, :sp_s_168_2
      remove_column :sp_bsbs, :sp_s_168_3
      remove_column :sp_bsbs, :sp_s_168_4
      remove_column :sp_bsbs, :sp_s_168_5
      remove_column :sp_bsbs, :sp_s_168_6
      remove_column :sp_bsbs, :sp_s_168_7
      remove_column :sp_bsbs, :sp_s_168_8
      remove_column :sp_bsbs, :sp_s_168_9
      remove_column :sp_bsbs, :sp_s_169_0
      remove_column :sp_bsbs, :sp_s_169_1
      remove_column :sp_bsbs, :sp_s_169_2
      remove_column :sp_bsbs, :sp_s_169_3
      remove_column :sp_bsbs, :sp_s_169_4
      remove_column :sp_bsbs, :sp_s_169_5
      remove_column :sp_bsbs, :sp_s_169_6
      remove_column :sp_bsbs, :sp_s_169_7
      remove_column :sp_bsbs, :sp_s_169_8
      remove_column :sp_bsbs, :sp_s_169_9
      remove_column :sp_bsbs, :sp_s_170_0
      remove_column :sp_bsbs, :sp_s_170_1
      remove_column :sp_bsbs, :sp_s_170_2
      remove_column :sp_bsbs, :sp_s_170_3
      remove_column :sp_bsbs, :sp_s_170_4
      remove_column :sp_bsbs, :sp_s_170_5
      remove_column :sp_bsbs, :sp_s_170_6
      remove_column :sp_bsbs, :sp_s_170_7
      remove_column :sp_bsbs, :sp_s_170_8
      remove_column :sp_bsbs, :sp_s_170_9
      remove_column :sp_bsbs, :sp_s_171_0
      remove_column :sp_bsbs, :sp_s_171_1
      remove_column :sp_bsbs, :sp_s_171_2
      remove_column :sp_bsbs, :sp_s_171_3
      remove_column :sp_bsbs, :sp_s_171_4
      remove_column :sp_bsbs, :sp_s_171_5
      remove_column :sp_bsbs, :sp_s_171_6
      remove_column :sp_bsbs, :sp_s_171_7
      remove_column :sp_bsbs, :sp_s_171_8
      remove_column :sp_bsbs, :sp_s_171_9
      remove_column :sp_bsbs, :sp_s_172_0
      remove_column :sp_bsbs, :sp_s_172_1
      remove_column :sp_bsbs, :sp_s_172_2
      remove_column :sp_bsbs, :sp_s_172_3
      remove_column :sp_bsbs, :sp_s_172_4
      remove_column :sp_bsbs, :sp_s_172_5
      remove_column :sp_bsbs, :sp_s_172_6
      remove_column :sp_bsbs, :sp_s_172_7
      remove_column :sp_bsbs, :sp_s_172_8
      remove_column :sp_bsbs, :sp_s_172_9
      remove_column :sp_bsbs, :sp_s_173_0
      remove_column :sp_bsbs, :sp_s_173_1
      remove_column :sp_bsbs, :sp_s_173_2
      remove_column :sp_bsbs, :sp_s_173_3
      remove_column :sp_bsbs, :sp_s_173_4
      remove_column :sp_bsbs, :sp_s_173_5
      remove_column :sp_bsbs, :sp_s_173_6
      remove_column :sp_bsbs, :sp_s_173_7
      remove_column :sp_bsbs, :sp_s_173_8
      remove_column :sp_bsbs, :sp_s_173_9
      remove_column :sp_bsbs, :sp_s_174_0
      remove_column :sp_bsbs, :sp_s_174_1
      remove_column :sp_bsbs, :sp_s_174_2
      remove_column :sp_bsbs, :sp_s_174_3
      remove_column :sp_bsbs, :sp_s_174_4
      remove_column :sp_bsbs, :sp_s_174_5
      remove_column :sp_bsbs, :sp_s_174_6
      remove_column :sp_bsbs, :sp_s_174_7
      remove_column :sp_bsbs, :sp_s_174_8
      remove_column :sp_bsbs, :sp_s_174_9
      remove_column :sp_bsbs, :sp_s_175_0
      remove_column :sp_bsbs, :sp_s_175_1
      remove_column :sp_bsbs, :sp_s_175_2
      remove_column :sp_bsbs, :sp_s_175_3
      remove_column :sp_bsbs, :sp_s_175_4
      remove_column :sp_bsbs, :sp_s_175_5
      remove_column :sp_bsbs, :sp_s_175_6
      remove_column :sp_bsbs, :sp_s_175_7
      remove_column :sp_bsbs, :sp_s_175_8
      remove_column :sp_bsbs, :sp_s_175_9
      remove_column :sp_bsbs, :sp_s_176_0
      remove_column :sp_bsbs, :sp_s_176_1
      remove_column :sp_bsbs, :sp_s_176_2
      remove_column :sp_bsbs, :sp_s_176_3
      remove_column :sp_bsbs, :sp_s_176_4
      remove_column :sp_bsbs, :sp_s_176_5
      remove_column :sp_bsbs, :sp_s_176_6
      remove_column :sp_bsbs, :sp_s_176_7
      remove_column :sp_bsbs, :sp_s_176_8
      remove_column :sp_bsbs, :sp_s_176_9
      remove_column :sp_bsbs, :sp_s_177_0
      remove_column :sp_bsbs, :sp_s_177_1
      remove_column :sp_bsbs, :sp_s_177_2
      remove_column :sp_bsbs, :sp_s_177_3
      remove_column :sp_bsbs, :sp_s_177_4
      remove_column :sp_bsbs, :sp_s_177_5
      remove_column :sp_bsbs, :sp_s_177_6
      remove_column :sp_bsbs, :sp_s_177_7
      remove_column :sp_bsbs, :sp_s_177_8
      remove_column :sp_bsbs, :sp_s_177_9
      remove_column :sp_bsbs, :sp_s_178_0
      remove_column :sp_bsbs, :sp_s_178_1
      remove_column :sp_bsbs, :sp_s_178_2
      remove_column :sp_bsbs, :sp_s_178_3
      remove_column :sp_bsbs, :sp_s_178_4
      remove_column :sp_bsbs, :sp_s_178_5
      remove_column :sp_bsbs, :sp_s_178_6
      remove_column :sp_bsbs, :sp_s_178_7
      remove_column :sp_bsbs, :sp_s_178_8
      remove_column :sp_bsbs, :sp_s_178_9
      remove_column :sp_bsbs, :sp_s_179_0
      remove_column :sp_bsbs, :sp_s_179_1
      remove_column :sp_bsbs, :sp_s_179_2
      remove_column :sp_bsbs, :sp_s_179_3
      remove_column :sp_bsbs, :sp_s_179_4
      remove_column :sp_bsbs, :sp_s_179_5
      remove_column :sp_bsbs, :sp_s_179_6
      remove_column :sp_bsbs, :sp_s_179_7
      remove_column :sp_bsbs, :sp_s_179_8
      remove_column :sp_bsbs, :sp_s_179_9
      remove_column :sp_bsbs, :sp_s_180_0
      remove_column :sp_bsbs, :sp_s_180_1
      remove_column :sp_bsbs, :sp_s_180_2
      remove_column :sp_bsbs, :sp_s_180_3
      remove_column :sp_bsbs, :sp_s_180_4
      remove_column :sp_bsbs, :sp_s_180_5
      remove_column :sp_bsbs, :sp_s_180_6
      remove_column :sp_bsbs, :sp_s_180_7
      remove_column :sp_bsbs, :sp_s_180_8
      remove_column :sp_bsbs, :sp_s_180_9
      remove_column :sp_bsbs, :sp_s_181_0
      remove_column :sp_bsbs, :sp_s_181_1
      remove_column :sp_bsbs, :sp_s_181_2
      remove_column :sp_bsbs, :sp_s_181_3
      remove_column :sp_bsbs, :sp_s_181_4
      remove_column :sp_bsbs, :sp_s_181_5
      remove_column :sp_bsbs, :sp_s_181_6
      remove_column :sp_bsbs, :sp_s_181_7
      remove_column :sp_bsbs, :sp_s_181_8
      
  end

  def down
  end
end
