class ChangeSpBsbSJc < ActiveRecord::Migration
  def up
      change_column :sp_bsbs, :sp_s_110_0, :text
      change_column :sp_bsbs, :sp_s_111_0, :text
      change_column :sp_bsbs, :sp_s_112_0, :text
      change_column :sp_bsbs, :sp_s_113_0, :text
      change_column :sp_bsbs, :sp_s_114_0, :text
      change_column :sp_bsbs, :sp_s_115_0, :text
      change_column :sp_bsbs, :sp_s_116_0, :text
      change_column :sp_bsbs, :sp_s_117_0, :text
      change_column :sp_bsbs, :sp_s_118_0, :text
      change_column :sp_bsbs, :sp_s_119_0, :text
      change_column :sp_bsbs, :sp_s_120_0, :text
      change_column :sp_bsbs, :sp_s_121_0, :text
      change_column :sp_bsbs, :sp_s_122_0, :text
      change_column :sp_bsbs, :sp_s_123_0, :text
      change_column :sp_bsbs, :sp_s_124_0, :text
      change_column :sp_bsbs, :sp_s_125_0, :text
      change_column :sp_bsbs, :sp_s_126_0, :text
      change_column :sp_bsbs, :sp_s_127_0, :text
      change_column :sp_bsbs, :sp_s_128_0, :text
      change_column :sp_bsbs, :sp_s_129_0, :text
      change_column :sp_bsbs, :sp_s_130_0, :text
      change_column :sp_bsbs, :sp_s_131_0, :text
      change_column :sp_bsbs, :sp_s_132_0, :text
      change_column :sp_bsbs, :sp_s_133_0, :text
      change_column :sp_bsbs, :sp_s_134_0, :text
      change_column :sp_bsbs, :sp_s_135_0, :text
      change_column :sp_bsbs, :sp_s_136_0, :text
      change_column :sp_bsbs, :sp_s_137_0, :text
      change_column :sp_bsbs, :sp_s_138_0, :text
      change_column :sp_bsbs, :sp_s_139_0, :text
      change_column :sp_bsbs, :sp_s_140_0, :text
      change_column :sp_bsbs, :sp_s_110_2, :text
      change_column :sp_bsbs, :sp_s_111_2, :text
      change_column :sp_bsbs, :sp_s_112_2, :text
      change_column :sp_bsbs, :sp_s_113_2, :text
      change_column :sp_bsbs, :sp_s_114_2, :text
      change_column :sp_bsbs, :sp_s_115_2, :text
      change_column :sp_bsbs, :sp_s_116_2, :text
      change_column :sp_bsbs, :sp_s_117_2, :text
      change_column :sp_bsbs, :sp_s_118_2, :text
      change_column :sp_bsbs, :sp_s_119_2, :text
      change_column :sp_bsbs, :sp_s_120_2, :text
      change_column :sp_bsbs, :sp_s_121_2, :text
      change_column :sp_bsbs, :sp_s_122_2, :text
      change_column :sp_bsbs, :sp_s_123_2, :text
      change_column :sp_bsbs, :sp_s_124_2, :text
      change_column :sp_bsbs, :sp_s_125_2, :text
      change_column :sp_bsbs, :sp_s_126_2, :text
      change_column :sp_bsbs, :sp_s_127_2, :text
      change_column :sp_bsbs, :sp_s_128_2, :text
      change_column :sp_bsbs, :sp_s_129_2, :text
      change_column :sp_bsbs, :sp_s_130_2, :text
      change_column :sp_bsbs, :sp_s_131_2, :text
      change_column :sp_bsbs, :sp_s_132_2, :text
      change_column :sp_bsbs, :sp_s_133_2, :text
      change_column :sp_bsbs, :sp_s_134_2, :text
      change_column :sp_bsbs, :sp_s_135_2, :text
      change_column :sp_bsbs, :sp_s_136_2, :text
      change_column :sp_bsbs, :sp_s_137_2, :text
      change_column :sp_bsbs, :sp_s_138_2, :text
      change_column :sp_bsbs, :sp_s_139_2, :text
      change_column :sp_bsbs, :sp_s_140_2, :text
      change_column :sp_bsbs, :sp_s_110_3, :text
      change_column :sp_bsbs, :sp_s_111_3, :text
      change_column :sp_bsbs, :sp_s_112_3, :text
      change_column :sp_bsbs, :sp_s_113_3, :text
      change_column :sp_bsbs, :sp_s_114_3, :text
      change_column :sp_bsbs, :sp_s_115_3, :text
      change_column :sp_bsbs, :sp_s_116_3, :text
      change_column :sp_bsbs, :sp_s_117_3, :text
      change_column :sp_bsbs, :sp_s_118_3, :text
      change_column :sp_bsbs, :sp_s_119_3, :text
      change_column :sp_bsbs, :sp_s_120_3, :text
      change_column :sp_bsbs, :sp_s_121_3, :text
      change_column :sp_bsbs, :sp_s_122_3, :text
      change_column :sp_bsbs, :sp_s_123_3, :text
      change_column :sp_bsbs, :sp_s_124_3, :text
      change_column :sp_bsbs, :sp_s_125_3, :text
      change_column :sp_bsbs, :sp_s_126_3, :text
      change_column :sp_bsbs, :sp_s_127_3, :text
      change_column :sp_bsbs, :sp_s_128_3, :text
      change_column :sp_bsbs, :sp_s_129_3, :text
      change_column :sp_bsbs, :sp_s_130_3, :text
      change_column :sp_bsbs, :sp_s_131_3, :text
      change_column :sp_bsbs, :sp_s_132_3, :text
      change_column :sp_bsbs, :sp_s_133_3, :text
      change_column :sp_bsbs, :sp_s_134_3, :text
      change_column :sp_bsbs, :sp_s_135_3, :text
      change_column :sp_bsbs, :sp_s_136_3, :text
      change_column :sp_bsbs, :sp_s_137_3, :text
      change_column :sp_bsbs, :sp_s_138_3, :text
      change_column :sp_bsbs, :sp_s_139_3, :text
      change_column :sp_bsbs, :sp_s_140_3, :text
      change_column :sp_bsbs, :sp_s_52, :text
      change_column :sp_bsbs, :sp_s_53, :text
      change_column :sp_bsbs, :sp_s_54, :text
      
  end

  def down
  end
end
