class DropSomeColumn < ActiveRecord::Migration
  def change 
  remove_column :wtyp_czbs,:fxpj_1
  remove_column :wtyp_czbs,:fxpj_2
  remove_column :wtyp_czbs,:fxpj_3
  remove_column :wtyp_czbs,:cpkzqk_1
  remove_column :wtyp_czbs,:cpkzqk_2
  remove_column :wtyp_czbs,:cpkzqk_3
  remove_column :wtyp_czbs,:cpkzqk_4
  remove_column :wtyp_czbs,:cpkzqk_5
  remove_column :wtyp_czbs,:cpkzqk_6
  remove_column :wtyp_czbs,:cpkzqk_7
  remove_column :wtyp_czbs,:cpkzqk_8
  remove_column :wtyp_czbs,:cpkzqk_9
  remove_column :wtyp_czbs,:cpkzqk_10
  remove_column :wtyp_czbs,:cpkzqk_11
  remove_column :wtyp_czbs,:cpkzqk_12
  remove_column :wtyp_czbs,:cpkzqk_13
  remove_column :wtyp_czbs,:cpkzqk_14
  remove_column :wtyp_czbs,:cpkzqk_15
  remove_column :wtyp_czbs,:cpkzqk_16
  remove_column :wtyp_czbs,:cpkzqk_17
  remove_column :wtyp_czbs,:cpkzqk_18
  remove_column :wtyp_czbs,:cpkzqk_19
  remove_column :wtyp_czbs,:pczgfc_1
  remove_column :wtyp_czbs,:pczgfc_2
  remove_column :wtyp_czbs,:pczgfc_3
  remove_column :wtyp_czbs,:pczgfc_4
  remove_column :wtyp_czbs,:pczgfc_5
  remove_column :wtyp_czbs,:pczgfc_6
  remove_column :wtyp_czbs,:pczgfc_7
  remove_column :wtyp_czbs,:pczgfc_8
  remove_column :wtyp_czbs,:pczgfc_9
  remove_column :wtyp_czbs,:xzcfqk_1
  remove_column :wtyp_czbs,:xzcfqk_2
  remove_column :wtyp_czbs,:xzcfqk_3
  remove_column :wtyp_czbs,:xzcfqk_4
  remove_column :wtyp_czbs,:xzcfqk_5
  remove_column :wtyp_czbs,:xzcfqk_6
  remove_column :wtyp_czbs,:xzcfqk_7
  remove_column :wtyp_czbs,:xzcfqk_8
  remove_column :wtyp_czbs,:xzcfqk_9
  remove_column :wtyp_czbs,:xzcfqk_10
  remove_column :wtyp_czbs,:xzcfqk_11
  remove_column :wtyp_czbs,:xzcfqk_12
  remove_column :wtyp_czbs,:xzcfqk_13
  remove_column :wtyp_czbs,:xzcfqk_14
  remove_column :wtyp_czbs,:xzcfqk_15
  remove_column :wtyp_czbs,:xzcfqk_16
  remove_column :wtyp_czbs,:xzcfqk_17
  remove_column :wtyp_czbs,:xzcfqk_18
  remove_column :wtyp_czbs,:xzcfqk_19
  remove_column :wtyp_czbs,:xzcfqk_20
  remove_column :wtyp_czbs,:xzcfqk_21
  remove_column :wtyp_czbs,:jyjgzt_sc
  remove_column :wtyp_czbs,:qdhcczrq_sc
  remove_column :wtyp_czbs,:czwbrq_sc
  remove_column :wtyp_czbs,:fxpj_1_sc
  remove_column :wtyp_czbs,:fxpj_2_sc
  remove_column :wtyp_czbs,:fxpj_3_sc
  remove_column :wtyp_czbs,:cpkzqk_1_sc
  remove_column :wtyp_czbs,:cpkzqk_2_sc
  remove_column :wtyp_czbs,:cpkzqk_3_sc
  remove_column :wtyp_czbs,:cpkzqk_4_sc
  remove_column :wtyp_czbs,:cpkzqk_5_sc
  remove_column :wtyp_czbs,:cpkzqk_6_sc
  remove_column :wtyp_czbs,:cpkzqk_7_sc
  remove_column :wtyp_czbs,:cpkzqk_8_sc
  remove_column :wtyp_czbs,:cpkzqk_9_sc
  remove_column :wtyp_czbs,:cpkzqk_10_sc
  remove_column :wtyp_czbs,:cpkzqk_11_sc
  remove_column :wtyp_czbs,:cpkzqk_12_sc
  remove_column :wtyp_czbs,:cpkzqk_13_sc
  remove_column :wtyp_czbs,:cpkzqk_14_sc
  remove_column :wtyp_czbs,:cpkzqk_15_sc
  remove_column :wtyp_czbs,:cpkzqk_16_sc
  remove_column :wtyp_czbs,:cpkzqk_17_sc
  remove_column :wtyp_czbs,:cpkzqk_18_sc
  remove_column :wtyp_czbs,:cpkzqk_19_sc
  remove_column :wtyp_czbs,:pczgfc_1_sc
  remove_column :wtyp_czbs,:pczgfc_2_sc
  remove_column :wtyp_czbs,:pczgfc_3_sc
  remove_column :wtyp_czbs,:pczgfc_4_sc
  remove_column :wtyp_czbs,:pczgfc_5_sc
  remove_column :wtyp_czbs,:pczgfc_6_sc
  remove_column :wtyp_czbs,:pczgfc_7_sc
  remove_column :wtyp_czbs,:pczgfc_8_sc
  remove_column :wtyp_czbs,:pczgfc_9_sc
  remove_column :wtyp_czbs,:xzcfqk_1_sc
  remove_column :wtyp_czbs,:xzcfqk_2_sc
  remove_column :wtyp_czbs,:xzcfqk_3_sc
  remove_column :wtyp_czbs,:xzcfqk_4_sc
  remove_column :wtyp_czbs,:xzcfqk_5_sc
  remove_column :wtyp_czbs,:xzcfqk_6_sc
  remove_column :wtyp_czbs,:xzcfqk_7_sc
  remove_column :wtyp_czbs,:xzcfqk_8_sc
  remove_column :wtyp_czbs,:xzcfqk_9_sc
  remove_column :wtyp_czbs,:xzcfqk_10_sc
  remove_column :wtyp_czbs,:xzcfqk_11_sc
  remove_column :wtyp_czbs,:xzcfqk_12_sc
  remove_column :wtyp_czbs,:xzcfqk_13_sc
  remove_column :wtyp_czbs,:xzcfqk_14_sc
  remove_column :wtyp_czbs,:xzcfqk_15_sc
  remove_column :wtyp_czbs,:xzcfqk_16_sc
  remove_column :wtyp_czbs,:xzcfqk_17_sc
  remove_column :wtyp_czbs,:xzcfqk_18_sc
  remove_column :wtyp_czbs,:xzcfqk_19_sc
  remove_column :wtyp_czbs,:xzcfqk_20_sc
  remove_column :wtyp_czbs,:xzcfqk_21_sc
  remove_column :wtyp_czbs,:yytcr
  remove_column :wtyp_czbs,:yytcsj
  remove_column :wtyp_czbs,:yysdsj
  remove_column :wtyp_czbs,:yynr
  remove_column :wtyp_czbs,:djbm
  remove_column :wtyp_czbs,:djr
  remove_column :wtyp_czbs,:djsj
  remove_column :wtyp_czbs,:fjsqzk
  remove_column :wtyp_czbs,:yyczqk
  remove_column :wtyp_czbs,:thyy
  remove_column :wtyp_czbs,:jyjgzt
  remove_column :wtyp_czbs,:qdhcczrq
  remove_column :wtyp_czbs,:czwbrq
  remove_column :wtyp_czbs,:hccz_type
  remove_column :wtyp_czbs,:part_submit_flag1
  remove_column :wtyp_czbs,:part_submit_flag2
  remove_column :wtyp_czbs,:part_submit_flag3
  remove_column :wtyp_czbs,:part_submit_flag4
  remove_column :wtyp_czbs,:wtyp_czb_type





  end

end
